disabled_rules:
  # Currently raise errors:
  - cyclomatic_complexity
  - identifier_name
  - function_body_length
  - force_cast
  - force_try
  - line_length
  - file_length
  - type_body_length

identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 41
