name: Swift Unit Test CI

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: xcode-select /Applications/Xcode.app

    - name: Build and Test
      run: |
        xcodebuild -scheme Scribe -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' clean build test

